import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetStaticProps, GetStaticPropsContext } from 'next'
import { CharactersPage } from '@/views/characters-view'
import { Character } from '@/entities/viewer'
import { FC } from 'react'

export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
  const response = await fetch('https://rickandmortyapi.com/api/character')
  const data = await response.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  const characters: Character[] = data.results;

  return {
    props: {
      characters
    },
  }
}

const Characters: FC = ({ characters = null }: any) => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <CharactersPage characters={characters} />
  </div>
)

export default Characters
