import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { Error404Page } from '@/views/error-404-view/error-404-view'

const Custom404: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>404: Not Found</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Error404Page />
   </div>
  )
}

export default Custom404
