import Head from 'next/head'
import { NextPageWithLayout } from '@/shared/@types'
import { GetServerSideProps, GetStaticProps } from 'next'
import { LocationsPage } from '@/views/locations-view'

export const getServerSideProps = async (context: GetServerSideProps) => {
  const response = await fetch('https://rickandmortyapi.com/api/location')
  const data = await response.json();

  if (!data) {
    return {
      notFound: true
    }
  }

  const locations = data.results;

  return {
    props: {
      locations,
    },
  }
}

const Locations: NextPageWithLayout = ({ locations = null }: any) => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <LocationsPage locations={locations} />
  </div>
)

export default Locations;
